<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root>
	<ProjectExperiment>
		<window>
			<RelativeDocumentPlacement type="key">~&lt;XtraSerializer version="1.0" application="DockLayoutManager"&gt;
  &lt;property name="#LayoutVersion" isnull="true" /&gt;
  &lt;property name="$DockLayoutManager" iskey="true" value="DockLayoutManager"&gt;
    &lt;property name="AllowCustomization"&gt;false&lt;/property&gt;
    &lt;property name="EnableWin32Compatibility"&gt;true&lt;/property&gt;
    &lt;property name="FloatingDocumentContainer"&gt;DocumentHost&lt;/property&gt;
    &lt;property name="FloatingMode"&gt;Desktop&lt;/property&gt;
    &lt;property name="Items" iskey="true" value="3"&gt;
      &lt;property name="Item1" isnull="true" iskey="true"&gt;
        &lt;property name="DestroyOnClosingChildren"&gt;false&lt;/property&gt;
        &lt;property name="Orientation"&gt;Vertical&lt;/property&gt;
        &lt;property name="SerializableSelectedTabPageIndex"&gt;-1&lt;/property&gt;
        &lt;property name="AllowDrag"&gt;false&lt;/property&gt;
        &lt;property name="AllowFloat"&gt;false&lt;/property&gt;
        &lt;property name="SerializableDockSituation" iskey="true" value="0" /&gt;
        &lt;property name="SerializationInfo" isnull="true" iskey="true"&gt;
          &lt;property name="IsUserDefined"&gt;true&lt;/property&gt;
        &lt;/property&gt;
        &lt;property name="TypeName"&gt;LayoutGroup&lt;/property&gt;
        &lt;property name="ParentName" isnull="true" /&gt;
        &lt;property name="ParentCollectionName" isnull="true" /&gt;
        &lt;property name="Name"&gt;RootLayoutGroup2&lt;/property&gt;
      &lt;/property&gt;
      &lt;property name="Item2" isnull="true" iskey="true"&gt;
        &lt;property name="DestroyOnClosingChildren"&gt;false&lt;/property&gt;
        &lt;property name="SerializableSelectedTabPageIndex"&gt;0&lt;/property&gt;
        &lt;property name="SerializableDockSituation" iskey="true" value="0" /&gt;
        &lt;property name="SerializationInfo" isnull="true" iskey="true"&gt;
          &lt;property name="IsUserDefined"&gt;true&lt;/property&gt;
        &lt;/property&gt;
        &lt;property name="TypeName"&gt;DocumentGroup&lt;/property&gt;
        &lt;property name="ParentName"&gt;RootLayoutGroup2&lt;/property&gt;
        &lt;property name="ParentCollectionName" isnull="true" /&gt;
        &lt;property name="Name"&gt;WorkingArea&lt;/property&gt;
      &lt;/property&gt;
      &lt;property name="Item3" isnull="true" iskey="true"&gt;
        &lt;property name="MDILocation"&gt;0,0&lt;/property&gt;
        &lt;property name="MDISize"&gt;NaN,NaN&lt;/property&gt;
        &lt;property name="SerializableFloatingBounds"&gt;0,0,0,0&lt;/property&gt;
        &lt;property name="SerializableFloatingOffset"&gt;0,0&lt;/property&gt;
        &lt;property name="AllowClose"&gt;true&lt;/property&gt;
        &lt;property name="AllowFloat"&gt;true&lt;/property&gt;
        &lt;property name="IsActive"&gt;false&lt;/property&gt;
        &lt;property name="SerializableDockSituation" iskey="true" value="0" /&gt;
        &lt;property name="SerializationInfo" isnull="true" iskey="true" /&gt;
        &lt;property name="ToolTip" isnull="true" /&gt;
        &lt;property name="TypeName"&gt;DocumentPanel&lt;/property&gt;
        &lt;property name="ParentName"&gt;WorkingArea&lt;/property&gt;
        &lt;property name="ParentCollectionName" isnull="true" /&gt;
        &lt;property name="DocumentGroup.Pinned" OwnerType="DevExpress.Xpf.Docking.DocumentGroup" DependencyPropertyType="System.Boolean"&gt;false&lt;/property&gt;
        &lt;property name="Name"&gt;Instrumentatioǹ7c̀567a5fec̀2d̀f1a2̀2d̀47f4̀2d̀aefd̀2d̀a8c21919cbbc̀2f̀3&lt;/property&gt;
        &lt;property name="SerializableMDIBounds"&gt;0,0,NaN,NaN&lt;/property&gt;
        &lt;property name="TabCaption" type="System.String"&gt;turnlamp&lt;/property&gt;
        &lt;property name="Caption" type="System.String"&gt;turnlamp&lt;/property&gt;
      &lt;/property&gt;
    &lt;/property&gt;
    &lt;property name="ManualClosedPanelsBarVisibility"&gt;false&lt;/property&gt;
    &lt;property name="ShowFloatWindowsInTaskbar"&gt;true&lt;/property&gt;
    &lt;property name="RestoreLayoutOptions.FloatPanelsRestoreOffset" OwnerType="DevExpress.Xpf.Docking.RestoreLayoutOptions" DependencyPropertyType="System.Windows.Point"&gt;521,164&lt;/property&gt;
  &lt;/property&gt;
&lt;/XtraSerializer&gt;</RelativeDocumentPlacement>
		</window>
		<viewflags>
			<Name type="key">turnlamp.CDE</Name>
			<ViewFlags type="key">1</ViewFlags>
			<item>
				<Name type="key">CalculatedVariables.vdp</Name>
				<ViewFlags type="key">1</ViewFlags>
			</item>
			<item>
				<Name type="key">turnlamp</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment Layouts</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">turnlamp.cdc</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">turnlamp.lay</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Hardware Configurations</Name>
					<ViewFlags type="key">1</ViewFlags>
					<item>
						<Name type="key">cec186a2-0abb-4b89-a49c-1dd6a31b6fb1</Name>
						<ViewFlags type="key">1</ViewFlags>
						<item>
							<Name type="key">turnlamp.sdf</Name>
							<ViewFlags type="key">1</ViewFlags>
							<item>
								<Name type="key">turnlamp.vdp</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
							<item>
								<Name type="key">.metadata</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
							<item>
								<Name type="key">turnlamp.map</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
							<item>
								<Name type="key">turnlamp.trc</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
							<item>
								<Name type="key">turnlamp.dsbuildinfo</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
							<item>
								<Name type="key">turnlamp.osa</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
							<item>
								<Name type="key">Data Sets</Name>
								<ViewFlags type="key">1</ViewFlags>
							</item>
						</item>
					</item>
					<item>
						<Name type="key">41743ca9-85c8-494d-9da6-985582389a6e</Name>
						<ViewFlags type="key">1</ViewFlags>
						<item>
							<Name type="key">cec186a2-0abb-4b89-a49c-1dd6a31b6fb1</Name>
							<ViewFlags type="key">1</ViewFlags>
						</item>
					</item>
				</item>
				<item>
					<Name type="key">Variable Descriptions</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Data Sets</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Mappings</Name>
					<ViewFlags type="key">5</ViewFlags>
					<item>
						<Name type="key">.metadata</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
					<item>
						<Name type="key">TurnLampMapping.xml</Name>
						<ViewFlags type="key">1</ViewFlags>
					</item>
				</item>
				<item>
					<Name type="key">Measurement Data</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Variable Filters</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Label Lists</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Reports</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Python Scripts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Signal Generators</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">BusNavigator</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">XIL API EESPorts</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
			<item>
				<Name type="key">AutomationCustomData.json</Name>
				<ViewFlags type="key">1</ViewFlags>
			</item>
			<item>
				<Name type="key">Events</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Experiment.events</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
		</viewflags>
	</ProjectExperiment>
	<BusNavigator>
		<Documents Version="1"/>
	</BusNavigator>
	<SignalEditor>
		<OpenSignalDescriptionSets Version="1"/>
		<OpenSignalGenerators Version="1"/>
		<Documents Version="1"/>
	</SignalEditor>
	<Instrumentation>
		<Layouts Version="3">
			<Layout1>
				<Data type="key">turnlamp.lay|1|567a5fec-f1a2-47f4-aefd-a8c21919cbbc/3|2:d</Data>
			</Layout1>
		</Layouts>
	</Instrumentation>
	<XILAPIEESPort>
		<ErrorConfigurationDocuments Version="1"/>
	</XILAPIEESPort>
	<PythonScriptComponent/>
</Root>