name: 'Stop EC2 Runner'
description: 'Stop or terminate an EC2 runner instance based on conditions'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  instance-id:
    description: 'EC2 Instance ID to stop/terminate'
    required: true
  shutdown-behavior:
    description: 'Shutdown behavior (stop or terminate)'
    required: true
  job-result:
    description: 'Result of the job that ran on the runner'
    required: true
  failed-job-not-terminate:
    description: 'Whether to not terminate (delete) the instance on job failure'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Stop EC2 runner
      shell: bash
      run: |
        # Handle instance based on conditions
        if [ "${{ inputs.shutdown-behavior }}" == "stop" ] || \
           ([ "${{ inputs.job-result }}" == "failure" ] && ${{ inputs.failed-job-not-terminate }}); then
          echo "Stopping EC2 instance..."
          aws ec2 stop-instances \
            --instance-ids "${{ inputs.instance-id }}"
        else
          echo "Terminating EC2 instance..."
          aws ec2 terminate-instances \
            --instance-ids "${{ inputs.instance-id }}"
        fi
