"""Type stub file for OpenTASDK variables. DO NOT EDIT - GENERATED FILE."""

from typing import Any, Dict, Protocol, Union
import numpy as np
from openta.common.quantity import Quantity

class v_EGOProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Dist_Fellow_to_EGOProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class d_FellowProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class a_Fellow_NegativeProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MinimalDistance_mProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class delta_velocity_fellow_km_hProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class distance_fellow_mProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class ManeuverStartProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class ManeuverStopProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class ResetProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Fellow1LengthProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Fellow1CenterOffsetProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class TTC_sProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Dist_Long_mProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_10Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_3Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_4Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_5Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_6Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_7Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_8Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_9Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class ManeuverStateProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class ManeuverTime_sProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class s_Veh_Road_mProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Collision_Flag_0NoCollision_1CollisionProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Collision_Flag_Held_0NoCollision_1CollisionProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class v_Rel_Collision_Point_Total_m_s_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class d_Total_Fellows_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class v_Fellows_km_h_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Pos_x_Fellows_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Pos_y_Fellows_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class s_Fellows_Ref_Scheduler_m_1Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class v_Fellows_km_h_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Height_m_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_ID_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Length_m_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_x_deg_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_y_deg_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Orientation_z_deg_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_x_m_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_y_m_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Position_z_m_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Type_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Vehicle_Type_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_10_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_1_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_2_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_3_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_4_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_5_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_6_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_7_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_8_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class MovObj_Width_m_9_2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class a_x_Vehicle_CoG_m_s2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class a_y_Vehicle_CoG_m_s2Protocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Pos_x_Vehicle_CoorSys_E_mProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class Pos_y_Vehicle_CoorSys_E_mProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class s_Vehicle_mProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class v_x_Vehicle_CoG_km_hProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class v_Total_Vehicle_km_hProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class CONTROL_OSI_SUBSYSTEMProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class v_total_vehicleProtocol(Protocol):
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, val: Union[float, Quantity, Any]) -> None: ...
    @property
    def quantity(self) -> Quantity: ...
    def __str__(self) -> str: ...

class VariablesCollection:
    v_EGO: v_EGOProtocol
    Dist_Fellow_to_EGO: Dist_Fellow_to_EGOProtocol
    d_Fellow: d_FellowProtocol
    a_Fellow_Negative: a_Fellow_NegativeProtocol
    MinimalDistance_m: MinimalDistance_mProtocol
    delta_velocity_fellow_km_h: delta_velocity_fellow_km_hProtocol
    distance_fellow_m: distance_fellow_mProtocol
    ManeuverStart: ManeuverStartProtocol
    ManeuverStop: ManeuverStopProtocol
    Reset: ResetProtocol
    Fellow1Length: Fellow1LengthProtocol
    Fellow1CenterOffset: Fellow1CenterOffsetProtocol
    TTC_s: TTC_sProtocol
    Dist_Long_m: Dist_Long_mProtocol
    MovObj_Height_m_10: MovObj_Height_m_10Protocol
    MovObj_Height_m_1: MovObj_Height_m_1Protocol
    MovObj_Height_m_2: MovObj_Height_m_2Protocol
    MovObj_Height_m_3: MovObj_Height_m_3Protocol
    MovObj_Height_m_4: MovObj_Height_m_4Protocol
    MovObj_Height_m_5: MovObj_Height_m_5Protocol
    MovObj_Height_m_6: MovObj_Height_m_6Protocol
    MovObj_Height_m_7: MovObj_Height_m_7Protocol
    MovObj_Height_m_8: MovObj_Height_m_8Protocol
    MovObj_Height_m_9: MovObj_Height_m_9Protocol
    MovObj_ID_10: MovObj_ID_10Protocol
    MovObj_ID_1: MovObj_ID_1Protocol
    MovObj_ID_2: MovObj_ID_2Protocol
    MovObj_ID_3: MovObj_ID_3Protocol
    MovObj_ID_4: MovObj_ID_4Protocol
    MovObj_ID_5: MovObj_ID_5Protocol
    MovObj_ID_6: MovObj_ID_6Protocol
    MovObj_ID_7: MovObj_ID_7Protocol
    MovObj_ID_8: MovObj_ID_8Protocol
    MovObj_ID_9: MovObj_ID_9Protocol
    MovObj_Length_m_10: MovObj_Length_m_10Protocol
    MovObj_Length_m_1: MovObj_Length_m_1Protocol
    MovObj_Length_m_2: MovObj_Length_m_2Protocol
    MovObj_Length_m_3: MovObj_Length_m_3Protocol
    MovObj_Length_m_4: MovObj_Length_m_4Protocol
    MovObj_Length_m_5: MovObj_Length_m_5Protocol
    MovObj_Length_m_6: MovObj_Length_m_6Protocol
    MovObj_Length_m_7: MovObj_Length_m_7Protocol
    MovObj_Length_m_8: MovObj_Length_m_8Protocol
    MovObj_Length_m_9: MovObj_Length_m_9Protocol
    MovObj_Orientation_x_deg_10: MovObj_Orientation_x_deg_10Protocol
    MovObj_Orientation_x_deg_1: MovObj_Orientation_x_deg_1Protocol
    MovObj_Orientation_x_deg_2: MovObj_Orientation_x_deg_2Protocol
    MovObj_Orientation_x_deg_3: MovObj_Orientation_x_deg_3Protocol
    MovObj_Orientation_x_deg_4: MovObj_Orientation_x_deg_4Protocol
    MovObj_Orientation_x_deg_5: MovObj_Orientation_x_deg_5Protocol
    MovObj_Orientation_x_deg_6: MovObj_Orientation_x_deg_6Protocol
    MovObj_Orientation_x_deg_7: MovObj_Orientation_x_deg_7Protocol
    MovObj_Orientation_x_deg_8: MovObj_Orientation_x_deg_8Protocol
    MovObj_Orientation_x_deg_9: MovObj_Orientation_x_deg_9Protocol
    MovObj_Orientation_y_deg_10: MovObj_Orientation_y_deg_10Protocol
    MovObj_Orientation_y_deg_1: MovObj_Orientation_y_deg_1Protocol
    MovObj_Orientation_y_deg_2: MovObj_Orientation_y_deg_2Protocol
    MovObj_Orientation_y_deg_3: MovObj_Orientation_y_deg_3Protocol
    MovObj_Orientation_y_deg_4: MovObj_Orientation_y_deg_4Protocol
    MovObj_Orientation_y_deg_5: MovObj_Orientation_y_deg_5Protocol
    MovObj_Orientation_y_deg_6: MovObj_Orientation_y_deg_6Protocol
    MovObj_Orientation_y_deg_7: MovObj_Orientation_y_deg_7Protocol
    MovObj_Orientation_y_deg_8: MovObj_Orientation_y_deg_8Protocol
    MovObj_Orientation_y_deg_9: MovObj_Orientation_y_deg_9Protocol
    MovObj_Orientation_z_deg_10: MovObj_Orientation_z_deg_10Protocol
    MovObj_Orientation_z_deg_1: MovObj_Orientation_z_deg_1Protocol
    MovObj_Orientation_z_deg_2: MovObj_Orientation_z_deg_2Protocol
    MovObj_Orientation_z_deg_3: MovObj_Orientation_z_deg_3Protocol
    MovObj_Orientation_z_deg_4: MovObj_Orientation_z_deg_4Protocol
    MovObj_Orientation_z_deg_5: MovObj_Orientation_z_deg_5Protocol
    MovObj_Orientation_z_deg_6: MovObj_Orientation_z_deg_6Protocol
    MovObj_Orientation_z_deg_7: MovObj_Orientation_z_deg_7Protocol
    MovObj_Orientation_z_deg_8: MovObj_Orientation_z_deg_8Protocol
    MovObj_Orientation_z_deg_9: MovObj_Orientation_z_deg_9Protocol
    MovObj_Position_x_m_10: MovObj_Position_x_m_10Protocol
    MovObj_Position_x_m_1: MovObj_Position_x_m_1Protocol
    MovObj_Position_x_m_2: MovObj_Position_x_m_2Protocol
    MovObj_Position_x_m_3: MovObj_Position_x_m_3Protocol
    MovObj_Position_x_m_4: MovObj_Position_x_m_4Protocol
    MovObj_Position_x_m_5: MovObj_Position_x_m_5Protocol
    MovObj_Position_x_m_6: MovObj_Position_x_m_6Protocol
    MovObj_Position_x_m_7: MovObj_Position_x_m_7Protocol
    MovObj_Position_x_m_8: MovObj_Position_x_m_8Protocol
    MovObj_Position_x_m_9: MovObj_Position_x_m_9Protocol
    MovObj_Position_y_m_10: MovObj_Position_y_m_10Protocol
    MovObj_Position_y_m_1: MovObj_Position_y_m_1Protocol
    MovObj_Position_y_m_2: MovObj_Position_y_m_2Protocol
    MovObj_Position_y_m_3: MovObj_Position_y_m_3Protocol
    MovObj_Position_y_m_4: MovObj_Position_y_m_4Protocol
    MovObj_Position_y_m_5: MovObj_Position_y_m_5Protocol
    MovObj_Position_y_m_6: MovObj_Position_y_m_6Protocol
    MovObj_Position_y_m_7: MovObj_Position_y_m_7Protocol
    MovObj_Position_y_m_8: MovObj_Position_y_m_8Protocol
    MovObj_Position_y_m_9: MovObj_Position_y_m_9Protocol
    MovObj_Position_z_m_10: MovObj_Position_z_m_10Protocol
    MovObj_Position_z_m_1: MovObj_Position_z_m_1Protocol
    MovObj_Position_z_m_2: MovObj_Position_z_m_2Protocol
    MovObj_Position_z_m_3: MovObj_Position_z_m_3Protocol
    MovObj_Position_z_m_4: MovObj_Position_z_m_4Protocol
    MovObj_Position_z_m_5: MovObj_Position_z_m_5Protocol
    MovObj_Position_z_m_6: MovObj_Position_z_m_6Protocol
    MovObj_Position_z_m_7: MovObj_Position_z_m_7Protocol
    MovObj_Position_z_m_8: MovObj_Position_z_m_8Protocol
    MovObj_Position_z_m_9: MovObj_Position_z_m_9Protocol
    MovObj_Type_10: MovObj_Type_10Protocol
    MovObj_Type_1: MovObj_Type_1Protocol
    MovObj_Type_2: MovObj_Type_2Protocol
    MovObj_Type_3: MovObj_Type_3Protocol
    MovObj_Type_4: MovObj_Type_4Protocol
    MovObj_Type_5: MovObj_Type_5Protocol
    MovObj_Type_6: MovObj_Type_6Protocol
    MovObj_Type_7: MovObj_Type_7Protocol
    MovObj_Type_8: MovObj_Type_8Protocol
    MovObj_Type_9: MovObj_Type_9Protocol
    MovObj_Vehicle_Type_10: MovObj_Vehicle_Type_10Protocol
    MovObj_Vehicle_Type_1: MovObj_Vehicle_Type_1Protocol
    MovObj_Vehicle_Type_2: MovObj_Vehicle_Type_2Protocol
    MovObj_Vehicle_Type_3: MovObj_Vehicle_Type_3Protocol
    MovObj_Vehicle_Type_4: MovObj_Vehicle_Type_4Protocol
    MovObj_Vehicle_Type_5: MovObj_Vehicle_Type_5Protocol
    MovObj_Vehicle_Type_6: MovObj_Vehicle_Type_6Protocol
    MovObj_Vehicle_Type_7: MovObj_Vehicle_Type_7Protocol
    MovObj_Vehicle_Type_8: MovObj_Vehicle_Type_8Protocol
    MovObj_Vehicle_Type_9: MovObj_Vehicle_Type_9Protocol
    MovObj_Width_m_10: MovObj_Width_m_10Protocol
    MovObj_Width_m_1: MovObj_Width_m_1Protocol
    MovObj_Width_m_2: MovObj_Width_m_2Protocol
    MovObj_Width_m_3: MovObj_Width_m_3Protocol
    MovObj_Width_m_4: MovObj_Width_m_4Protocol
    MovObj_Width_m_5: MovObj_Width_m_5Protocol
    MovObj_Width_m_6: MovObj_Width_m_6Protocol
    MovObj_Width_m_7: MovObj_Width_m_7Protocol
    MovObj_Width_m_8: MovObj_Width_m_8Protocol
    MovObj_Width_m_9: MovObj_Width_m_9Protocol
    ManeuverState: ManeuverStateProtocol
    ManeuverTime_s: ManeuverTime_sProtocol
    s_Veh_Road_m: s_Veh_Road_mProtocol
    Collision_Flag_0NoCollision_1Collision: Collision_Flag_0NoCollision_1CollisionProtocol
    Collision_Flag_Held_0NoCollision_1Collision: Collision_Flag_Held_0NoCollision_1CollisionProtocol
    v_Rel_Collision_Point_Total_m_s_1: v_Rel_Collision_Point_Total_m_s_1Protocol
    d_Total_Fellows_m_1: d_Total_Fellows_m_1Protocol
    v_Fellows_km_h_1: v_Fellows_km_h_1Protocol
    Pos_x_Fellows_m_1: Pos_x_Fellows_m_1Protocol
    Pos_y_Fellows_m_1: Pos_y_Fellows_m_1Protocol
    s_Fellows_Ref_Scheduler_m_1: s_Fellows_Ref_Scheduler_m_1Protocol
    v_Fellows_km_h_1_2: v_Fellows_km_h_1_2Protocol
    MovObj_Height_m_10_2: MovObj_Height_m_10_2Protocol
    MovObj_Height_m_1_2: MovObj_Height_m_1_2Protocol
    MovObj_Height_m_2_2: MovObj_Height_m_2_2Protocol
    MovObj_Height_m_3_2: MovObj_Height_m_3_2Protocol
    MovObj_Height_m_4_2: MovObj_Height_m_4_2Protocol
    MovObj_Height_m_5_2: MovObj_Height_m_5_2Protocol
    MovObj_Height_m_6_2: MovObj_Height_m_6_2Protocol
    MovObj_Height_m_7_2: MovObj_Height_m_7_2Protocol
    MovObj_Height_m_8_2: MovObj_Height_m_8_2Protocol
    MovObj_Height_m_9_2: MovObj_Height_m_9_2Protocol
    MovObj_ID_10_2: MovObj_ID_10_2Protocol
    MovObj_ID_1_2: MovObj_ID_1_2Protocol
    MovObj_ID_2_2: MovObj_ID_2_2Protocol
    MovObj_ID_3_2: MovObj_ID_3_2Protocol
    MovObj_ID_4_2: MovObj_ID_4_2Protocol
    MovObj_ID_5_2: MovObj_ID_5_2Protocol
    MovObj_ID_6_2: MovObj_ID_6_2Protocol
    MovObj_ID_7_2: MovObj_ID_7_2Protocol
    MovObj_ID_8_2: MovObj_ID_8_2Protocol
    MovObj_ID_9_2: MovObj_ID_9_2Protocol
    MovObj_Length_m_10_2: MovObj_Length_m_10_2Protocol
    MovObj_Length_m_1_2: MovObj_Length_m_1_2Protocol
    MovObj_Length_m_2_2: MovObj_Length_m_2_2Protocol
    MovObj_Length_m_3_2: MovObj_Length_m_3_2Protocol
    MovObj_Length_m_4_2: MovObj_Length_m_4_2Protocol
    MovObj_Length_m_5_2: MovObj_Length_m_5_2Protocol
    MovObj_Length_m_6_2: MovObj_Length_m_6_2Protocol
    MovObj_Length_m_7_2: MovObj_Length_m_7_2Protocol
    MovObj_Length_m_8_2: MovObj_Length_m_8_2Protocol
    MovObj_Length_m_9_2: MovObj_Length_m_9_2Protocol
    MovObj_Orientation_x_deg_10_2: MovObj_Orientation_x_deg_10_2Protocol
    MovObj_Orientation_x_deg_1_2: MovObj_Orientation_x_deg_1_2Protocol
    MovObj_Orientation_x_deg_2_2: MovObj_Orientation_x_deg_2_2Protocol
    MovObj_Orientation_x_deg_3_2: MovObj_Orientation_x_deg_3_2Protocol
    MovObj_Orientation_x_deg_4_2: MovObj_Orientation_x_deg_4_2Protocol
    MovObj_Orientation_x_deg_5_2: MovObj_Orientation_x_deg_5_2Protocol
    MovObj_Orientation_x_deg_6_2: MovObj_Orientation_x_deg_6_2Protocol
    MovObj_Orientation_x_deg_7_2: MovObj_Orientation_x_deg_7_2Protocol
    MovObj_Orientation_x_deg_8_2: MovObj_Orientation_x_deg_8_2Protocol
    MovObj_Orientation_x_deg_9_2: MovObj_Orientation_x_deg_9_2Protocol
    MovObj_Orientation_y_deg_10_2: MovObj_Orientation_y_deg_10_2Protocol
    MovObj_Orientation_y_deg_1_2: MovObj_Orientation_y_deg_1_2Protocol
    MovObj_Orientation_y_deg_2_2: MovObj_Orientation_y_deg_2_2Protocol
    MovObj_Orientation_y_deg_3_2: MovObj_Orientation_y_deg_3_2Protocol
    MovObj_Orientation_y_deg_4_2: MovObj_Orientation_y_deg_4_2Protocol
    MovObj_Orientation_y_deg_5_2: MovObj_Orientation_y_deg_5_2Protocol
    MovObj_Orientation_y_deg_6_2: MovObj_Orientation_y_deg_6_2Protocol
    MovObj_Orientation_y_deg_7_2: MovObj_Orientation_y_deg_7_2Protocol
    MovObj_Orientation_y_deg_8_2: MovObj_Orientation_y_deg_8_2Protocol
    MovObj_Orientation_y_deg_9_2: MovObj_Orientation_y_deg_9_2Protocol
    MovObj_Orientation_z_deg_10_2: MovObj_Orientation_z_deg_10_2Protocol
    MovObj_Orientation_z_deg_1_2: MovObj_Orientation_z_deg_1_2Protocol
    MovObj_Orientation_z_deg_2_2: MovObj_Orientation_z_deg_2_2Protocol
    MovObj_Orientation_z_deg_3_2: MovObj_Orientation_z_deg_3_2Protocol
    MovObj_Orientation_z_deg_4_2: MovObj_Orientation_z_deg_4_2Protocol
    MovObj_Orientation_z_deg_5_2: MovObj_Orientation_z_deg_5_2Protocol
    MovObj_Orientation_z_deg_6_2: MovObj_Orientation_z_deg_6_2Protocol
    MovObj_Orientation_z_deg_7_2: MovObj_Orientation_z_deg_7_2Protocol
    MovObj_Orientation_z_deg_8_2: MovObj_Orientation_z_deg_8_2Protocol
    MovObj_Orientation_z_deg_9_2: MovObj_Orientation_z_deg_9_2Protocol
    MovObj_Position_x_m_10_2: MovObj_Position_x_m_10_2Protocol
    MovObj_Position_x_m_1_2: MovObj_Position_x_m_1_2Protocol
    MovObj_Position_x_m_2_2: MovObj_Position_x_m_2_2Protocol
    MovObj_Position_x_m_3_2: MovObj_Position_x_m_3_2Protocol
    MovObj_Position_x_m_4_2: MovObj_Position_x_m_4_2Protocol
    MovObj_Position_x_m_5_2: MovObj_Position_x_m_5_2Protocol
    MovObj_Position_x_m_6_2: MovObj_Position_x_m_6_2Protocol
    MovObj_Position_x_m_7_2: MovObj_Position_x_m_7_2Protocol
    MovObj_Position_x_m_8_2: MovObj_Position_x_m_8_2Protocol
    MovObj_Position_x_m_9_2: MovObj_Position_x_m_9_2Protocol
    MovObj_Position_y_m_10_2: MovObj_Position_y_m_10_2Protocol
    MovObj_Position_y_m_1_2: MovObj_Position_y_m_1_2Protocol
    MovObj_Position_y_m_2_2: MovObj_Position_y_m_2_2Protocol
    MovObj_Position_y_m_3_2: MovObj_Position_y_m_3_2Protocol
    MovObj_Position_y_m_4_2: MovObj_Position_y_m_4_2Protocol
    MovObj_Position_y_m_5_2: MovObj_Position_y_m_5_2Protocol
    MovObj_Position_y_m_6_2: MovObj_Position_y_m_6_2Protocol
    MovObj_Position_y_m_7_2: MovObj_Position_y_m_7_2Protocol
    MovObj_Position_y_m_8_2: MovObj_Position_y_m_8_2Protocol
    MovObj_Position_y_m_9_2: MovObj_Position_y_m_9_2Protocol
    MovObj_Position_z_m_10_2: MovObj_Position_z_m_10_2Protocol
    MovObj_Position_z_m_1_2: MovObj_Position_z_m_1_2Protocol
    MovObj_Position_z_m_2_2: MovObj_Position_z_m_2_2Protocol
    MovObj_Position_z_m_3_2: MovObj_Position_z_m_3_2Protocol
    MovObj_Position_z_m_4_2: MovObj_Position_z_m_4_2Protocol
    MovObj_Position_z_m_5_2: MovObj_Position_z_m_5_2Protocol
    MovObj_Position_z_m_6_2: MovObj_Position_z_m_6_2Protocol
    MovObj_Position_z_m_7_2: MovObj_Position_z_m_7_2Protocol
    MovObj_Position_z_m_8_2: MovObj_Position_z_m_8_2Protocol
    MovObj_Position_z_m_9_2: MovObj_Position_z_m_9_2Protocol
    MovObj_Type_10_2: MovObj_Type_10_2Protocol
    MovObj_Type_1_2: MovObj_Type_1_2Protocol
    MovObj_Type_2_2: MovObj_Type_2_2Protocol
    MovObj_Type_3_2: MovObj_Type_3_2Protocol
    MovObj_Type_4_2: MovObj_Type_4_2Protocol
    MovObj_Type_5_2: MovObj_Type_5_2Protocol
    MovObj_Type_6_2: MovObj_Type_6_2Protocol
    MovObj_Type_7_2: MovObj_Type_7_2Protocol
    MovObj_Type_8_2: MovObj_Type_8_2Protocol
    MovObj_Type_9_2: MovObj_Type_9_2Protocol
    MovObj_Vehicle_Type_10_2: MovObj_Vehicle_Type_10_2Protocol
    MovObj_Vehicle_Type_1_2: MovObj_Vehicle_Type_1_2Protocol
    MovObj_Vehicle_Type_2_2: MovObj_Vehicle_Type_2_2Protocol
    MovObj_Vehicle_Type_3_2: MovObj_Vehicle_Type_3_2Protocol
    MovObj_Vehicle_Type_4_2: MovObj_Vehicle_Type_4_2Protocol
    MovObj_Vehicle_Type_5_2: MovObj_Vehicle_Type_5_2Protocol
    MovObj_Vehicle_Type_6_2: MovObj_Vehicle_Type_6_2Protocol
    MovObj_Vehicle_Type_7_2: MovObj_Vehicle_Type_7_2Protocol
    MovObj_Vehicle_Type_8_2: MovObj_Vehicle_Type_8_2Protocol
    MovObj_Vehicle_Type_9_2: MovObj_Vehicle_Type_9_2Protocol
    MovObj_Width_m_10_2: MovObj_Width_m_10_2Protocol
    MovObj_Width_m_1_2: MovObj_Width_m_1_2Protocol
    MovObj_Width_m_2_2: MovObj_Width_m_2_2Protocol
    MovObj_Width_m_3_2: MovObj_Width_m_3_2Protocol
    MovObj_Width_m_4_2: MovObj_Width_m_4_2Protocol
    MovObj_Width_m_5_2: MovObj_Width_m_5_2Protocol
    MovObj_Width_m_6_2: MovObj_Width_m_6_2Protocol
    MovObj_Width_m_7_2: MovObj_Width_m_7_2Protocol
    MovObj_Width_m_8_2: MovObj_Width_m_8_2Protocol
    MovObj_Width_m_9_2: MovObj_Width_m_9_2Protocol
    a_x_Vehicle_CoG_m_s2: a_x_Vehicle_CoG_m_s2Protocol
    a_y_Vehicle_CoG_m_s2: a_y_Vehicle_CoG_m_s2Protocol
    Pos_x_Vehicle_CoorSys_E_m: Pos_x_Vehicle_CoorSys_E_mProtocol
    Pos_y_Vehicle_CoorSys_E_m: Pos_y_Vehicle_CoorSys_E_mProtocol
    s_Vehicle_m: s_Vehicle_mProtocol
    v_x_Vehicle_CoG_km_h: v_x_Vehicle_CoG_km_hProtocol
    v_Total_Vehicle_km_h: v_Total_Vehicle_km_hProtocol
    CONTROL_OSI_SUBSYSTEM: CONTROL_OSI_SUBSYSTEMProtocol
    v_total_vehicle: v_total_vehicleProtocol
    def __getitem__(self, key: str) -> Any: ...
    def __getattr__(self, key: str) -> Any: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...

