name: Brute Force Execution Dispatcher with TA SDK

on:
  workflow_dispatch:

permissions:
  actions: write # Required to call other workflows

jobs:
  brute-force-execution:
    runs-on: ubuntu-latest
    strategy:
      # Add any additional parameters needed for your dSPACE job
      matrix:
        ami-id: ['ami-0bb50ff1709190a42']   # Linux TA_SDK AMI
        # ami-id: ['ami-0dc0f13e8dbac09d4'] # Windows TA_SDK AMI
        instance-type: ['t3.2xlarge'] # recommended: t3.large or larger
        shutdown-behavior: ['terminate'] # or 'stop'
        ebs-volume-size: [500] # EBS volume size in GB
        failed-job-not-terminate: [true] # Do NOT terminate EC2 Instance when the job fails
        workflow-id: ['one-time-simulation-and-test-with-ta-sdk-using-aws-linux-runner.yaml']
        python-sdk-dir: ['PythonSDK_Turnlamp', 'PythonSDK_Turnlamp_AllPass']
        openta-testenv-config-file: ['testdata/testenv_veos_linux.yaml']
        param-1: ['value1', 'value2'] # Example additional parameter
        param-2: ['valueA'] # Example additional parameter
      # Allow all combinations to run even if one fails
      fail-fast: false

    steps:
      - name: Call dSPACE Windows Runner
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '${{ matrix.workflow-id }}',
              ref: context.ref,
              inputs: {
                'ami-id': '${{ matrix.ami-id }}',
                'instance-type': '${{ matrix.instance-type }}',
                'shutdown-behavior': '${{ matrix.shutdown-behavior }}',
                'ebs-volume-size': '${{ matrix.ebs-volume-size }}',
                'failed-job-not-terminate': '${{ matrix.failed-job-not-terminate }}',
                'python-sdk-dir': '${{ matrix.python-sdk-dir }}',
                'openta-testenv-config-file': '${{ matrix.openta-testenv-config-file }}'
              }
            });
