name: Build Windows Runner AMI

on:
  workflow_dispatch:

env:
  AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ami_id: ${{ steps.build-ami.outputs.ami_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.AWS_PROFILE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ env.AWS_PROFILE }}

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Build AMI
        id: build-ami
        run: |
          packer init config/windows-github-runner.pkr.hcl
          AMI_ID=$(packer build -machine-readable config/windows-github-runner.pkr.hcl | grep 'artifact,0,id' | cut -d, -f6 | cut -d: -f2)
          if [ -z "$AMI_ID" ]; then
            echo "Failed to get AMI ID from Packer build output"
            exit 1
          fi
          echo "ami_id=${AMI_ID}" >> $GITHUB_OUTPUT
          echo "Built AMI ID: ${AMI_ID}"
