name: dSPACE AWS On-Demand Windows Runner

on:
  workflow_dispatch:
    inputs:
      ami-id:
        description: 'Windows AMI ID'
        type: choice
        required: false
        default: 'ami-0cfdba0116ec18ad9' # Replace with your default Windows AMI
        options:
          - 'ami-0cfdba0116ec18ad9' # Windows with dSPACE ControlDesk
          - 'ami-03f341346ac05fc46' # Windows_Server-2022-English-Full-Base-2025.07.09
      instance-type:
        description: 'EC2 Instance Type (recommended: t3.large or larger)'
        type: choice
        required: false
        default: 't3.2xlarge'
        options:
          - 't3.large'
          - 't3.xlarge'
          - 't3.2xlarge'
          - 'm5.large'
          - 'm5.xlarge'
      shutdown-behavior:
        description: 'Shutdown Behavior for EC2 Instance'
        type: choice
        required: false
        default: 'terminate'
        options:
          - 'terminate'
          - 'stop'
      ebs-volume-size:
        description: 'EBS Volume Size in GB (default: 500)'
        type: number
        required: false
        default: 500
      failed-job-not-terminate:
        description: 'Do NOT terminate EC2 Instance when the job fails'
        type: boolean
        required: false
        default: true
      # Add any additional parameters needed for your dSPACE job
      cdn-project-subpath:
        description: 'ControlDesk Project Subpath'
        type: string
        required: false
        default: 'ControlDesk/CD_Traffic.ZIP' # Replace with your default project subpath
      param1:
        description: 'Parameter 1'
        type: string
        required: false
        default: 'A' # Replace with your default value
      param2:
        description: 'Parameter 2'
        type: string
        required: false
        default: 'a' # Replace with your default value

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  start-runner:
    name: Start self-hosted EC2 Runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 runner
        id: start-ec2-runner
        run: |
          # Get GitHub runner registration token
          TOKEN_RESPONSE=$(curl -sL \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token")
          REGISTRATION_TOKEN=$(echo $TOKEN_RESPONSE | jq -r .token)

          # Set runner label
          RUNNER_LABEL=github-run-id-"${{ github.run_id }}"
          echo "RUNNER_LABEL=$RUNNER_LABEL" >> $GITHUB_ENV

          # Create user-data powershell script
          USER_DATA=$(cat <<EOF
          <powershell>
          New-Item -ItemType Directory -Path "C:\\actions-runner" -Force
          Set-Location -Path "C:\\actions-runner"

          Start-Transcript -Path "C:\\actions-runner\\startup.log" -Append
          Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.326.0/actions-runner-win-x64-2.326.0.zip -OutFile actions-runner-win-x64-2.326.0.zip

          if ((Get-FileHash -Path actions-runner-win-x64-2.326.0.zip -Algorithm SHA256).Hash.ToUpper() -ne '539d48815f8ecda6903755025d5b578f919a32692b731d85a9a24419fe4dbd9e'.ToUpper()) {
            throw 'Computed checksum did not match'
          }

          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::ExtractToDirectory("\$PWD\\actions-runner-win-x64-2.326.0.zip", "\$PWD")

          # With --ephemeral option, the runner will be removed after the job is done
          # With --unattended option, the runner will not prompt for any input
          .\config.cmd --url https://github.com/${{ github.repository }} --token ${REGISTRATION_TOKEN} --labels ${RUNNER_LABEL} --unattended --ephemeral

          Start-Process -FilePath ".\run.cmd" -WindowStyle Hidden

          Stop-Transcript
          </powershell>
          EOF
          )

          # With --key-name option, replace with your SSH key pair name for RDP password decryption
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id "${{ inputs.ami-id }}" \
            --instance-type "${{ inputs.instance-type }}" \
            --subnet-id "subnet-0aa2561258482ae58" \
            --security-group-ids "sg-0a3740d437cb92517" \
            --associate-public-ip-address \
            --iam-instance-profile "Name=data-replay-346-AccessInstanceProfile-cCDJrbRcf8M0" \
            --block-device-mappings "[{\"DeviceName\":\"/dev/sda1\",\"Ebs\":{\"VolumeSize\":${{ inputs.ebs-volume-size }},\"VolumeType\":\"gp3\"}}]" \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${RUNNER_LABEL}},{Key=GitHubRepository,Value=${{ github.repository }}}]" \
            --query 'Instances[0].InstanceId' \
            --instance-initiated-shutdown-behavior "${{ inputs.shutdown-behavior }}" \
            --key-name "vew" \
            --user-data "${USER_DATA}" \
            --metadata-options "HttpTokens=required,HttpEndpoint=enabled" \
            --output text)

          # Set outputs
          echo "label=${RUNNER_LABEL}" >> $GITHUB_OUTPUT
          echo "ec2-instance-id=${INSTANCE_ID}" >> $GITHUB_OUTPUT


  do-dspace-job:
    name: Do dSPACE job on the Runner
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Only fetch the latest commit to save time

      - name: Hello dSPACE World
        shell: powershell
        run: |
          Write-Host "Hello dSPACE World!"
          # exit 1 # exit with failure
          # exit 0 # exit with success
      
      - name: Start ControlDesk
        shell: powershell
        run: |
          $script = @"
          import win32com.client
          import pythoncom
          import os
          import sys
          import logging
          import zipfile

          # Configure logging
          logging.basicConfig(
              level=logging.INFO,
              format='%(asctime)s - %(levelname)s - %(message)s'
          )

          # Get parameters from environment variables
          project_subpath = os.environ['CDN_PROJECT_SUBPATH']
          param1 = os.environ['PARAM1']
          param2 = os.environ['PARAM2']

          # Get GITHUB WORKSPACE Path
          github_workspace = os.environ['GITHUB_WORKSPACE']

          try:
              logging.info(f"Starting ControlDesk automation")
              logging.info(f"Project subpath: {project_subpath}")
              logging.info(f"Parameters: param1={param1}, param2={param2}")
              
              pythoncom.CoInitialize()
              cdn_app = None

              logging.info("Initializing ControlDesk application")
              for i in range(3):  # Retry up to 3 times
                  logging.info(f"Attempt {i+1} to start ControlDesk")
                  try:
                      cdn_app = win32com.client.Dispatch("ControlDeskNG.Application")
                      break  # Exit loop if successful
                  except Exception as e:
                      logging.error(f"Failed to start ControlDesk: {e}")
              else:
                  logging.error("Could not start ControlDesk after 3 attempts")
                  sys.exit(1)

              # Convert relative path to absolute path and normalize slashes
              zip_abspath = os.path.abspath(os.path.join(github_workspace, project_subpath))
              zip_abspath = zip_abspath.replace('/', '\\')  # Convert to Windows path format
              
              # ZIP ファイルと同じディレクトリに展開
              logging.info(f"Extracting zip: {zip_abspath}")
              extract_dir = os.path.splitext(zip_abspath)[0] # Directory without .zip extension
              with zipfile.ZipFile(zip_abspath, 'r') as zip_ref:
                  zip_ref.extractall(extract_dir)
              project_abspath = os.path.join(extract_dir, os.path.splitext(os.path.basename(zip_abspath))[0] + ".CDP")

              logging.info(f"Opening project: {project_abspath}")
              cdn_app.OpenProject(project_abspath)
              logging.info("Project opened successfully")
              
              # Here you can use param1 and param2 for your ControlDesk operations
              # For example:
              # cdn_app.DoSomething(param1, param2)
              
              logging.info("Operations completed successfully")

              logging.info("Closing ControlDesk application")
              cdn_app.Quit(False)  # False = don't save changes
              logging.info("ControlDesk closed successfully")
              cdn_app = None
              
          except Exception as e:
              logging.error(f"Error in ControlDesk automation: {e}")
              import traceback
              traceback.print_exc()
              sys.exit(1)
              
          finally:
              pythoncom.CoUninitialize()
              logging.info("ControlDesk automation completed")
          "@

          # Set environment variables for the Python script
          $env:CDN_PROJECT_SUBPATH = "${{ inputs.cdn-project-subpath }}"
          $env:PARAM1 = "${{ inputs.param1 }}"
          $env:PARAM2 = "${{ inputs.param2 }}"
          
          $scriptPath = "$env:TEMP\\start_cd.py"
          $script | Out-File -FilePath $scriptPath -Encoding UTF8
          python $scriptPath


  stop-runner:
    name: Stop self-hosted EC2 Runner
    needs:
      - start-runner # required to get output from the start-runner job
      - do-dspace-job # required to wait when the main job is done  
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        run: |
          # Handle instance based on conditions
          if [ "${{ inputs.shutdown-behavior }}" == "stop" ] || \
             ([ "${{ needs.do-dspace-job.result }}" == "failure" ] && ${{ inputs.failed-job-not-terminate }}); then
            echo "Stopping EC2 instance..."
            aws ec2 stop-instances \
              --instance-ids "${{ needs.start-runner.outputs.ec2-instance-id }}"
          else
            echo "Terminating EC2 instance..."
            aws ec2 terminate-instances \
              --instance-ids "${{ needs.start-runner.outputs.ec2-instance-id }}"
          fi
